# Generated by Django 5.0.3 on 2024-07-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'permissions': [('view_table', 'Can view table'), ('edit_table', 'Can edit table')]},
        ),
        migrations.AlterModelOptions(
            name='countryindicator',
            options={'permissions': [('view_table', 'Can view table'), ('edit_table', 'Can edit table')]},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'permissions': [('view_table', 'Can view table'), ('edit_table', 'Can edit table')]},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'permissions': [('view_table', 'Can view table'), ('edit_table', 'Can edit table')]},
        ),
        migrations.AlterModelOptions(
            name='researchpaper',
            options={'permissions': [('view_table', 'Can view table'), ('edit_table', 'Can edit table')]},
        ),
        migrations.AlterModelOptions(
            name='researchpaperauthor',
            options={'permissions': [('view_table', 'Can view table'), ('edit_table', 'Can edit table')]},
        ),
    ]
