# Generated by Django 5.0.3 on 2024-07-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0002_alter_country_options_alter_countryindicator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelOptions(
            name='countryindicator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={},
        ),
        migrations.AlterModelOptions(
            name='researchpaper',
            options={},
        ),
        migrations.AlterModelOptions(
            name='researchpaperauthor',
            options={},
        ),
    ]
