# Generated by Django 5.0.3 on 2024-08-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0005_permissionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='researchpaperauthor',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='researchpaperauthor',
            name='research_paper',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso_code',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='base_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koe_db.country'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='currentPrices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='data_frequency_years',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='seasonally_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source',
            field=models.CharField(default='manual entry', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='indicator',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='koe_db.category'),
        ),
        migrations.CreateModel(
            name='CustomIndicatorComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField()),
                ('base_indicators', models.ManyToManyField(related_name='base_indicators', to='koe_db.indicator')),
                ('custom_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_indicator', to='koe_db.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('indicators', models.ManyToManyField(related_name='custom_tables', to='koe_db.indicator')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='regions',
            field=models.ManyToManyField(blank=True, to='koe_db.region'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koe_db.region'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.DecimalField(decimal_places=5, max_digits=20)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koe_db.indicator')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='koe_db.unit')),
            ],
        ),
        migrations.DeleteModel(
            name='CountryIndicator',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
        migrations.DeleteModel(
            name='ResearchPaper',
        ),
        migrations.DeleteModel(
            name='ResearchPaperAuthor',
        ),
    ]
