# Generated by Django 5.0.3 on 2024-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0006_category_region_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
    ]
