# Generated by Django 5.0.3 on 2025-01-29 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0007_alter_data_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField()),
                ('base_indicators', models.ManyToManyField(to='koe_db.indicator')),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_formula', to='koe_db.indicator')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomIndicatorComponent',
        ),
    ]
