# Generated by Django 5.0.3 on 2025-01-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0008_customindicator_delete_customindicatorcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='isEstimate',
            field=models.BooleanField(default=False),
        ),
    ]
