# Generated by Django 5.0.3 on 2025-01-31 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0009_indicator_isestimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='isEstimate',
        ),
        migrations.AddField(
            model_name='data',
            name='isEstimate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='koe_db.unit'),
        ),
    ]
