# Generated by Django 5.0.3 on 2025-01-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0011_auto_20250131_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='unit',
        ),
    ]
