# Generated by Django 5.1.6 on 2025-02-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0012_remove_data_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractionlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='PermissionRequest',
        ),
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
