# Generated by Django 5.1.6 on 2025-02-24 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0014_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DATA_UPDATE', 'Data Update'), ('INDICATOR_EDIT', 'Indicator Edit'), ('INDICATOR_CREATE', 'Indicator Create'), ('INDICATOR_DELETE', 'Indicator Delete'), ('FORMULA_UPDATE', 'Formula Update')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koe_db.indicator')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
