# Generated by Django 5.1.6 on 2025-03-05 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0015_actionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('public', 'Public Viewing'), ('unrestricted', 'Unrestricted Access'), ('organization', 'Organization Members'), ('restricted', 'Restricted Access')], default='public', help_text='Controls default permissions for this indicator', max_length=20)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_level', to='koe_db.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='koe_db.indicator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'indicator')},
            },
        ),
    ]
