# Generated by Django 5.1.6 on 2025-03-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0016_accesslevel_indicatorpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='level',
            field=models.CharField(choices=[('public', 'Public Viewing'), ('unrestricted', 'Unrestricted Access'), ('organization', 'Organization Members'), ('restricted', 'Restricted Access'), ('org_full_public', 'Organization Full Public')], default='public', help_text='Controls default permissions for this indicator', max_length=20),
        ),
    ]
