# Generated by Django 5.1.6 on 2025-03-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0018_userfavouriteindicators_userfavouritetables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavouriteindicators',
            name='indicators',
            field=models.ManyToManyField(to='koe_db.indicator'),
        ),
        migrations.AlterField(
            model_name='userfavouritetables',
            name='tables',
            field=models.ManyToManyField(to='koe_db.customtable'),
        ),
    ]
