# Generated by Django 5.1.6 on 2025-03-26 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0019_alter_userfavouriteindicators_indicators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('ECB', 'ECB Request'), ('CYSTAT', 'CyStat Request'), ('EUROSTAT', 'EuroStat Request')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='koe_db.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='EuroStatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eurostat_request', to='koe_db.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ECBRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=100)),
                ('parameters', models.JSONField()),
                ('frequency', models.CharField(max_length=20)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecb_request', to='koe_db.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='CyStatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('request_body', models.JSONField()),
                ('start_period', models.CharField(max_length=20)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cystat_request', to='koe_db.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('action_log', models.ForeignKey(blank=True, help_text='Reference to the ActionLog entry for data changes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='koe_db.actionlog')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='koe_db.workflow')),
            ],
        ),
    ]
