# Generated by Django 5.1.6 on 2025-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0020_workflow_eurostatrequest_ecbrequest_cystatrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='schedule_frequency',
        ),
        migrations.AddField(
            model_name='workflow',
            name='schedule_cron',
            field=models.CharField(default='0 0 1 * *', help_text="Cron-like syntax for scheduling (e.g., '0 9 * * 1' for every Monday at 9 AM)", max_length=100),
        ),
    ]
