# Generated by Django 5.1.6 on 2025-04-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0021_remove_workflow_schedule_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eurostatrequest',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='indicator',
        ),
        migrations.AddField(
            model_name='workflow',
            name='name',
            field=models.CharField(default='Default Workflow Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='schedule_cron',
            field=models.CharField(default='0 0 1 * *', max_length=100),
        ),
        migrations.CreateModel(
            name='CyStatIndicatorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_indices', models.JSONField()),
                ('cystat_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_mappings', to='koe_db.cystatrequest')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cystat_mappings', to='koe_db.indicator')),
            ],
            options={
                'unique_together': {('cystat_request', 'indicator')},
            },
        ),
        migrations.DeleteModel(
            name='ECBRequest',
        ),
        migrations.DeleteModel(
            name='EuroStatRequest',
        ),
    ]
