# Generated by Django 5.1.6 on 2025-04-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0022_remove_eurostatrequest_workflow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowrun',
            name='action_log',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='koe_db.workflowrun'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
