# Generated by Django 5.1.6 on 2025-04-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0023_remove_workflowrun_action_log_actionlog_run_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECBRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=100)),
                ('parameters', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=20)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecb_requests', to='koe_db.indicator')),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecb_request', to='koe_db.workflow')),
            ],
        ),
    ]
