# Generated by Django 5.1.6 on 2025-05-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0024_ecbrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroStatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The Eurostat API URL to fetch data from')),
                ('frequency', models.CharField(help_text="Data frequency (e.g., 'Annual', 'Monthly', 'Quarterly')", max_length=20)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eurostat_request', to='koe_db.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='EuroStatIndicatorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_values', models.JSONField(help_text='Mapping of dimension names to their selected values for this indicator')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eurostat_mappings', to='koe_db.indicator')),
                ('eurostat_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_mappings', to='koe_db.eurostatrequest')),
            ],
            options={
                'unique_together': {('eurostat_request', 'indicator')},
            },
        ),
    ]
