# Generated by Django 5.1.6 on 2025-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe_db', '0025_eurostatrequest_eurostatindicatormapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='frequency',
            field=models.CharField(choices=[('MINUTE', 'Per Minute'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Every 2 Months'), ('QUARTERLY', 'Quarterly'), ('TRIANNUAL', 'Every 4 Months'), ('SEMIANNUAL', 'Semiannual / Biannual'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom / Other')], default='CUSTOM', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='other_frequency',
            field=models.CharField(blank=True, help_text='Use this field if frequency is CUSTOM', max_length=50, null=True),
        ),
    ]
